# Generated by Django 5.1 on 2024-09-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_course_videos_user_enrollment_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URI', models.CharField(max_length=500)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_posts', to='posts.post')),
            ],
        ),
    ]
