# Generated by Django 5.1 on 2024-09-01 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_videos',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='user_enrollment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='user_enrollment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course_videos',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_course', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user_enrollment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user_enrollment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
