# Generated by Django 5.1 on 2024-09-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_alter_user_enrollment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_videos',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_course', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='user_enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='posts.post'),
        ),
    ]
