# Generated by Django 5.1 on 2024-09-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0065_alter_course_videos_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='user_enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user_enrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='course_videos',
        ),
        migrations.DeleteModel(
            name='notes',
        ),
        migrations.DeleteModel(
            name='user_enrollment',
        ),
    ]
