# Generated by Django 5.1 on 2024-09-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_course_videos_notes_user_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_videos',
        ),
    ]
