# Generated by Django 5.1 on 2024-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_delete_course_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='user_enrollment',
            old_name='user_id',
            new_name='user',
        ),
    ]
