# Generated by Django 5.0 on 2024-03-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_subheading',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='course_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
