# Generated by Django 5.0 on 2024-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_allcourses_course_subheading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_date',
            field=models.DateField(auto_now=True),
        ),
    ]
