# Generated by Django 5.0 on 2024-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allcourses_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_image',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
