# Generated by Django 5.0 on 2024-03-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_allcourses_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_enrollment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='course_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
