# Generated by Django 5.0 on 2024-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_allcourses_course_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
