# Generated by Django 5.0 on 2024-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_allcourses_course_total_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='allInstructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_email', models.CharField(max_length=100)),
                ('instructor_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
