# Generated by Django 5.0 on 2024-03-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_allinstructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='course_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.allinstructors'),
        ),
        migrations.AlterField(
            model_name='allinstructors',
            name='desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='allinstructors',
            name='instructor_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='allinstructors',
            name='instructor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
