# Generated by Django 5.0 on 2024-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_allcourses_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinstructors',
            name='total_courses',
            field=models.IntegerField(default=0),
        ),
    ]
